### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by d0geda** [jgarzik/pyminer#12]
Process Process-1:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\edast\Desktop\pyminer-master\pyminer.py", line 207, in miner_thread
    miner.loop()
  File "C:\Users\edast\Desktop\pyminer-master\pyminer.py", line 197, in loop
    rpc = BitcoinRPC(settings['host'], settings['port'],
KeyError: 'host'
Process Process-2:
Traceback (most recent call last):
  File "C:\Python27\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Python27\lib\multiprocessing\process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\edast\Desktop\pyminer-master\pyminer.py", line 207, in miner_thread
    miner.loop()
  File "C:\Users\edast\Desktop\pyminer-master\pyminer.py", line 197, in loop
    rpc = BitcoinRPC(settings['host'], settings['port'],
KeyError: 'host'
Traceback (most recent call last):
  File "C:\Users\edast\Desktop\pyminer-master\pyminer.py", line 221, in <module>
    time.sleep(1)                       # stagger threads
KeyboardInterrupt

**Comment by SKlayer** [comment]
i have the same fatal. and i try to solve..

**Comment by lewislin3** [comment]
same problem

**Comment by number9387** [comment]
Same issue, any idea on how to solve this so far?

**Comment by ORP967** [comment]
I have a working miner that uses the current "getworktemplate" in python 3. It is a code from (https://github.com/vsergeev) that I changed to check for a new block every 20 sc or so and start mining again every time a new block is detected. Currently getting 1.01KH/s on a Dell.
