### ISSUE TITLE
Program fails to be executed

### ISSUE THREAD

**Issue by klebermo** [jgarzik/pyminer#13]
When I try run this code in my computer, I am getting this error:

`Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "pyminer.py", line 207, in miner_thread
    miner.loop()
  File "pyminer.py", line 203, in loop
    self.iterate(rpc)
  File "pyminer.py", line 167, in iterate
    work = rpc.getwork()
  File "pyminer.py", line 76, in getwork
    return self.rpc('getwork', data)
  File "pyminer.py", line 56, in rpc
    resp = self.conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''`

the command I am running is this:

`python pyminer.py example-config.cfg`

In the configuration file, I use as rpcuser and rpcpassword, the username and password of the user I run the bitcoind.

I am using the version 2.7.12 of Python. I am not able to run this program with version 3.5.2 (I got the error:
`  File "pyminer.py", line 31
    MAX_NONCE = 1000000L
                       ^
SyntaxError: invalid syntax`
before the program exits).

**Comment by ORP967** [comment]
I have a working miner that uses the current "getworktemplate" in python 3. It is a code from (https://github.com/vsergeev) that I changed to check for a new block every 20 sc or so and start mining again every time a new block is detected. Currently getting 1.01KH/s on a Dell.
